/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as SignalerRouteImport } from './routes/signaler'
import { Route as SecuriteRouteImport } from './routes/securite'
import { Route as RecupererRouteImport } from './routes/recuperer'
import { Route as MesDossiersRouteImport } from './routes/mes-dossiers'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as AnnuaireRouteImport } from './routes/annuaire'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DossierCodeRouteImport } from './routes/dossier.$code'

const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalerRoute = SignalerRouteImport.update({
  id: '/signaler',
  path: '/signaler',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuriteRoute = SecuriteRouteImport.update({
  id: '/securite',
  path: '/securite',
  getParentRoute: () => rootRouteImport,
} as any)
const RecupererRoute = RecupererRouteImport.update({
  id: '/recuperer',
  path: '/recuperer',
  getParentRoute: () => rootRouteImport,
} as any)
const MesDossiersRoute = MesDossiersRouteImport.update({
  id: '/mes-dossiers',
  path: '/mes-dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnuaireRoute = AnnuaireRouteImport.update({
  id: '/annuaire',
  path: '/annuaire',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierCodeRoute = DossierCodeRouteImport.update({
  id: '/dossier/$code',
  path: '/dossier/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/annuaire': typeof AnnuaireRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/connexion': typeof ConnexionRoute
  '/mes-dossiers': typeof MesDossiersRoute
  '/recuperer': typeof RecupererRoute
  '/securite': typeof SecuriteRoute
  '/signaler': typeof SignalerRoute
  '/temoignages': typeof TemoignagesRoute
  '/dossier/$code': typeof DossierCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/annuaire': typeof AnnuaireRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/connexion': typeof ConnexionRoute
  '/mes-dossiers': typeof MesDossiersRoute
  '/recuperer': typeof RecupererRoute
  '/securite': typeof SecuriteRoute
  '/signaler': typeof SignalerRoute
  '/temoignages': typeof TemoignagesRoute
  '/dossier/$code': typeof DossierCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/annuaire': typeof AnnuaireRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/connexion': typeof ConnexionRoute
  '/mes-dossiers': typeof MesDossiersRoute
  '/recuperer': typeof RecupererRoute
  '/securite': typeof SecuriteRoute
  '/signaler': typeof SignalerRoute
  '/temoignages': typeof TemoignagesRoute
  '/dossier/$code': typeof DossierCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/annuaire'
    | '/comment-ca-marche'
    | '/connexion'
    | '/mes-dossiers'
    | '/recuperer'
    | '/securite'
    | '/signaler'
    | '/temoignages'
    | '/dossier/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/annuaire'
    | '/comment-ca-marche'
    | '/connexion'
    | '/mes-dossiers'
    | '/recuperer'
    | '/securite'
    | '/signaler'
    | '/temoignages'
    | '/dossier/$code'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/annuaire'
    | '/comment-ca-marche'
    | '/connexion'
    | '/mes-dossiers'
    | '/recuperer'
    | '/securite'
    | '/signaler'
    | '/temoignages'
    | '/dossier/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnnuaireRoute: typeof AnnuaireRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ConnexionRoute: typeof ConnexionRoute
  MesDossiersRoute: typeof MesDossiersRoute
  RecupererRoute: typeof RecupererRoute
  SecuriteRoute: typeof SecuriteRoute
  SignalerRoute: typeof SignalerRoute
  TemoignagesRoute: typeof TemoignagesRoute
  DossierCodeRoute: typeof DossierCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signaler': {
      id: '/signaler'
      path: '/signaler'
      fullPath: '/signaler'
      preLoaderRoute: typeof SignalerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/securite': {
      id: '/securite'
      path: '/securite'
      fullPath: '/securite'
      preLoaderRoute: typeof SecuriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperer': {
      id: '/recuperer'
      path: '/recuperer'
      fullPath: '/recuperer'
      preLoaderRoute: typeof RecupererRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-dossiers': {
      id: '/mes-dossiers'
      path: '/mes-dossiers'
      fullPath: '/mes-dossiers'
      preLoaderRoute: typeof MesDossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annuaire': {
      id: '/annuaire'
      path: '/annuaire'
      fullPath: '/annuaire'
      preLoaderRoute: typeof AnnuaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier/$code': {
      id: '/dossier/$code'
      path: '/dossier/$code'
      fullPath: '/dossier/$code'
      preLoaderRoute: typeof DossierCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnnuaireRoute: AnnuaireRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ConnexionRoute: ConnexionRoute,
  MesDossiersRoute: MesDossiersRoute,
  RecupererRoute: RecupererRoute,
  SecuriteRoute: SecuriteRoute,
  SignalerRoute: SignalerRoute,
  TemoignagesRoute: TemoignagesRoute,
  DossierCodeRoute: DossierCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
